services:
  app:
    image: ghcr.io/alfiosalanitri/flask-log-monitor:latest
    build:
      context: .
      args:
        APP_PORT: ${APP_PORT:-5000}
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app